-- Add habit-tracking metric types
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'SLEEP_HOURS';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'SLEEP_QUALITY';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'CALORIES';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'PROTEIN_G';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'WATER_ML';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'MOOD';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'ENERGY';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'SORENESS';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'STRESS';
