-- Expand BodyPart enum with muscle groups. The old parts (CHEST,
-- BACK_UPPER, BACK_LOWER, HIP) are kept for backward compat
-- but the new parts are what the UI renders.

-- First, the enum. Postgres doesn't let you ALTER TYPE ADD VALUE
-- inside a transaction in some versions, so we use IF NOT EXISTS.
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'PECTORAL';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'ABS';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'OBLIQUE_L';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'OBLIQUE_R';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'TRICEP_L';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'TRICEP_R';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'TRAPS';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'LAT_L';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'LAT_R';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'GLUTE_L';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'GLUTE_R';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'ADDUCTOR_L';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'ADDUCTOR_R';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'ABDUCTOR_L';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'ABDUCTOR_R';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'ROTATOR_CUFF_L';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'ROTATOR_CUFF_R';
