import { PrismaClient, ItemRarity, EquipSlot, ClassName } from './prisma.js';

const prisma = new PrismaClient();

/**
 * Seed catalog of equippable items. Every item gets its own unique
 * 64×64 PNG under /sprites/items/<id>.png — generated by the
 * sprite-generation pipeline from per-item prompt seeds in
 * web/public/sprites/items/MANIFEST.json. The previous convention
 * (one icon per class×slot) left the catalog with 19 shared
 * sprites; per-item sprites fix that.
 *
 * Stat curves per rarity (additive, applied to combat math):
 *   COMMON     :  1 stat ×  5-8
 *   UNCOMMON   :  2 stats × 10-15
 *   RARE      :  2 stats × 18-25
 *   EPIC      :  3 stats × 30-45
 *   LEGENDARY  :  4 stats × 55-75
 *   MYTHIC    :  5 stats × 90-120
 *
 * Class restrictions lock items to a single class so the rarity drop
 * matches the user's progression (a Juggernaut can't wear phantom
 * leathers). Items without a classRestriction are universally
 * equippable.
 *
 * Item-id naming:
 *   tron_<class>_<slot>     → Tron-era baseline (UNCOMMON, setId tron_set)
 *   shirt_<class>_basic     → old common tier (plain shirts per class)
 *   armor_<class>_<tier>    → old tiered body (warrior_1/2/3, rogue_1/2,
 *                             healer_1/2)
 *   head_<class>_<tier>     → old tiered helm/hood (warrior_1/3, rogue_1/3,
 *                             healer_1/3)
 *   weapon_<class>_<tier>   → old tiered weapons (warrior_1/2/4,
 *                             rogue_0/2, healer_1/3, burst_axe,
 *                             burst_dagger)
 *   shield_<class>_<tier>   → old tiered shields
 *   <slot>_<adjective>      → universal (no classRestriction)
 *
 * The sprite path for every item is `items/<id>.png` regardless of
 * which naming family the id comes from. This keeps the convention
 * flat — the GH Action reads MANIFEST.json, generates PNGs, drops
 * them into web/public/sprites/items/.
 */

type SeedItem = {
  id: string;
  name: string;
  description?: string;
  slot: EquipSlot;
  sprite: string;
  color: string;
  rarity: ItemRarity;
  stats: Record<string, number>;
  classRestriction?: ClassName | null;
  setId?: string | null;
};

// Helper to keep the seed table terse. sprite path is always
// items/<id>.png; the manifest pulls the prompt from the name.
const itemSprite = (id: string) => `items/${id}.png`;

const ITEMS: SeedItem[] = [
  // ============================================================
  // TRON SET — one item per (class, slot) combo, UNCOMMON baseline
  // ============================================================

  // ---- HEAD ----
  { id: 'tron_juggernaut_head', name: 'Iron Crown',            slot: 'HEAD', sprite: 'gear/head/juggernaut.png',    color: '#dc2626', rarity: 'UNCOMMON', stats: { '+DEF': 8, '+HP': 15 },                   classRestriction: 'JUGGERNAUT', setId: 'tron_set' },
  { id: 'tron_berserker_head',  name: 'Topknot Bind',          slot: 'HEAD', sprite: 'gear/head/berserker.png',     color: '#f55cc4', rarity: 'UNCOMMON', stats: { '+CRIT': 0.08, '+DEF': 5 },               classRestriction: 'BERSERKER', setId: 'tron_set' },
  { id: 'tron_phantom_head',    name: 'Cowl of Whispers',      slot: 'HEAD', sprite: 'gear/head/phantom.png',       color: '#9bff5c', rarity: 'UNCOMMON', stats: { '+EVA': 0.10, '+DISC': 0.05 },           classRestriction: 'PHANTOM',   setId: 'tron_set' },
  { id: 'tron_tracer_head',     name: 'Wind Wrap',             slot: 'HEAD', sprite: 'gear/head/tracer.png',        color: '#ff8c00', rarity: 'UNCOMMON', stats: { '+BURST': 0.10, '+EVA': 0.05 },          classRestriction: 'TRACER',    setId: 'tron_set' },
  { id: 'tron_scout_head',      name: 'Boonie Hat',            slot: 'HEAD', sprite: 'gear/head/scout.png',         color: '#ffc34d', rarity: 'UNCOMMON', stats: { '+DISC': 0.08, '+HEAL': 0.05 },          classRestriction: 'SCOUT',     setId: 'tron_set' },
  { id: 'tron_oracle_head',     name: 'Mind Circlet',          slot: 'HEAD', sprite: 'gear/head/oracle.png',        color: '#7d7bff', rarity: 'UNCOMMON', stats: { '+HEAL': 0.10, '+HP': 10 },              classRestriction: 'ORACLE',    setId: 'tron_set' },

  // ---- BODY ----
  { id: 'tron_juggernaut_body', name: 'Cuirass Plate',         slot: 'BODY', sprite: 'gear/body/juggernaut.png',    color: '#dc2626', rarity: 'UNCOMMON', stats: { '+DMG': 10, '+DEF': 8, '+HP': 20 },        classRestriction: 'JUGGERNAUT', setId: 'tron_set' },
  { id: 'tron_berserker_body',  name: 'Spiked Pauldron',       slot: 'BODY', sprite: 'gear/body/berserker.png',     color: '#f55cc4', rarity: 'UNCOMMON', stats: { '+CRIT': 0.10, '+DMG': 5, '+HP': 15 },    classRestriction: 'BERSERKER', setId: 'tron_set' },
  { id: 'tron_phantom_body',    name: 'Diagonal Wrap',         slot: 'BODY', sprite: 'gear/body/phantom.png',       color: '#9bff5c', rarity: 'UNCOMMON', stats: { '+EVA': 0.12, '+DEF': 6 },              classRestriction: 'PHANTOM',   setId: 'tron_set' },
  { id: 'tron_tracer_body',     name: 'Lightstep Top',         slot: 'BODY', sprite: 'gear/body/tracer.png',        color: '#ff8c00', rarity: 'UNCOMMON', stats: { '+BURST': 0.12, '+EVA': 0.05 },         classRestriction: 'TRACER',    setId: 'tron_set' },
  { id: 'tron_scout_body',      name: 'Quilted Chest Piece',   slot: 'BODY', sprite: 'gear/body/scout.png',         color: '#ffc34d', rarity: 'UNCOMMON', stats: { '+DISC': 0.10, '+HP': 15 },             classRestriction: 'SCOUT',     setId: 'tron_set' },
  { id: 'tron_oracle_body',     name: 'Folded Robes',          slot: 'BODY', sprite: 'gear/body/oracle.png',        color: '#7d7bff', rarity: 'UNCOMMON', stats: { '+HEAL': 0.12, '+HP': 18 },              classRestriction: 'ORACLE',    setId: 'tron_set' },

  // ---- HANDS ----
  { id: 'tron_juggernaut_hands', name: 'Heavy Gauntlets',      slot: 'HANDS', sprite: 'gear/hands/juggernaut.png',  color: '#dc2626', rarity: 'UNCOMMON', stats: { '+DMG': 8, '+DEF': 6 },                  classRestriction: 'JUGGERNAUT', setId: 'tron_set' },
  { id: 'tron_berserker_hands',  name: 'Studded Bracers',      slot: 'HANDS', sprite: 'gear/hands/berserker.png',   color: '#f55cc4', rarity: 'UNCOMMON', stats: { '+CRIT': 0.08, '+DMG': 4 },               classRestriction: 'BERSERKER', setId: 'tron_set' },
  { id: 'tron_phantom_hands',    name: 'Fingerless Gloves',    slot: 'HANDS', sprite: 'gear/hands/phantom.png',     color: '#9bff5c', rarity: 'UNCOMMON', stats: { '+EVA': 0.10, '+CRIT': 0.05 },            classRestriction: 'PHANTOM',   setId: 'tron_set' },
  { id: 'tron_tracer_hands',     name: 'Light Bracer',         slot: 'HANDS', sprite: 'gear/hands/tracer.png',      color: '#ff8c00', rarity: 'UNCOMMON', stats: { '+BURST': 0.10, '+EVA': 0.05 },           classRestriction: 'TRACER',    setId: 'tron_set' },
  { id: 'tron_scout_hands',      name: 'Archer Bracer',        slot: 'HANDS', sprite: 'gear/hands/scout.png',       color: '#ffc34d', rarity: 'UNCOMMON', stats: { '+CRIT': 0.06, '+DISC': 0.05 },           classRestriction: 'SCOUT',     setId: 'tron_set' },
  { id: 'tron_oracle_hands',     name: 'Hand Wraps',           slot: 'HANDS', sprite: 'gear/hands/oracle.png',      color: '#7d7bff', rarity: 'UNCOMMON', stats: { '+HEAL': 0.10, '+HP': 10 },             classRestriction: 'ORACLE',    setId: 'tron_set' },

  // ---- FEET ----
  { id: 'tron_juggernaut_feet', name: 'Sabatons',              slot: 'FEET', sprite: 'gear/feet/juggernaut.png',   color: '#dc2626', rarity: 'UNCOMMON', stats: { '+DEF': 6, '+HP': 12 },                   classRestriction: 'JUGGERNAUT', setId: 'tron_set' },
  { id: 'tron_berserker_feet',  name: 'Foot Wraps',           slot: 'FEET', sprite: 'gear/feet/berserker.png',    color: '#f55cc4', rarity: 'UNCOMMON', stats: { '+CRIT': 0.06, '+EVA': 0.05 },            classRestriction: 'BERSERKER', setId: 'tron_set' },
  { id: 'tron_phantom_feet',    name: 'Tabi Boots',           slot: 'FEET', sprite: 'gear/feet/phantom.png',      color: '#9bff5c', rarity: 'UNCOMMON', stats: { '+EVA': 0.10, '+DEF': 4 },               classRestriction: 'PHANTOM',   setId: 'tron_set' },
  { id: 'tron_tracer_feet',     name: 'Light Boots',          slot: 'FEET', sprite: 'gear/feet/tracer.png',       color: '#ff8c00', rarity: 'UNCOMMON', stats: { '+BURST': 0.10, '+HP': 8 },              classRestriction: 'TRACER',    setId: 'tron_set' },
  { id: 'tron_scout_feet',      name: 'Combat Boots',         slot: 'FEET', sprite: 'gear/feet/scout.png',        color: '#ffc34d', rarity: 'UNCOMMON', stats: { '+DISC': 0.08, '+DEF': 5 },              classRestriction: 'SCOUT',     setId: 'tron_set' },
  { id: 'tron_oracle_feet',     name: 'Sandals',              slot: 'FEET', sprite: 'gear/feet/oracle.png',       color: '#7d7bff', rarity: 'UNCOMMON', stats: { '+HEAL': 0.10, '+EVA': 0.05 },           classRestriction: 'ORACLE',    setId: 'tron_set' },

  // ---- OFF HAND — only juggernaut/berserker/scout get one ----
  { id: 'tron_juggernaut_off', name: 'Tower Shield',          slot: 'OFF', sprite: 'gear/off/juggernaut.png',     color: '#dc2626', rarity: 'UNCOMMON', stats: { '+DEF': 12, '+HP': 25 },                  classRestriction: 'JUGGERNAUT', setId: 'tron_set' },
  { id: 'tron_berserker_off',  name: 'Round Shield',          slot: 'OFF', sprite: 'gear/off/berserker.png',      color: '#f55cc4', rarity: 'UNCOMMON', stats: { '+DEF': 8, '+CRIT': 0.05 },               classRestriction: 'BERSERKER', setId: 'tron_set' },
  { id: 'tron_scout_off',      name: 'Round Buckler',         slot: 'OFF', sprite: 'gear/off/scout.png',          color: '#ffc34d', rarity: 'UNCOMMON', stats: { '+DEF': 6, '+DISC': 0.05 },              classRestriction: 'SCOUT',     setId: 'tron_set' },

  // ---- NECK ----
  { id: 'tron_juggernaut_neck', name: 'Iron Torque',           slot: 'NECK', sprite: 'gear/neck/juggernaut.png',   color: '#dc2626', rarity: 'UNCOMMON', stats: { '+DEF': 6, '+HP': 12 },                   classRestriction: 'JUGGERNAUT', setId: 'tron_set' },
  { id: 'tron_berserker_neck',  name: 'Fang Necklace',         slot: 'NECK', sprite: 'gear/neck/berserker.png',    color: '#f55cc4', rarity: 'UNCOMMON', stats: { '+CRIT': 0.06, '+DMG': 5 },               classRestriction: 'BERSERKER', setId: 'tron_set' },
  { id: 'tron_phantom_neck',    name: 'Cloth Scarf',           slot: 'NECK', sprite: 'gear/neck/phantom.png',      color: '#9bff5c', rarity: 'UNCOMMON', stats: { '+EVA': 0.08, '+DISC': 0.05 },           classRestriction: 'PHANTOM',   setId: 'tron_set' },
  { id: 'tron_tracer_neck',     name: 'Speed Charm',           slot: 'NECK', sprite: 'gear/neck/tracer.png',       color: '#ff8c00', rarity: 'UNCOMMON', stats: { '+BURST': 0.10, '+EVA': 0.05 },          classRestriction: 'TRACER',    setId: 'tron_set' },
  { id: 'tron_scout_neck',      name: 'Leather Strap',         slot: 'NECK', sprite: 'gear/neck/scout.png',        color: '#ffc34d', rarity: 'UNCOMMON', stats: { '+DISC': 0.08, '+HEAL': 0.05 },          classRestriction: 'SCOUT',     setId: 'tron_set' },
  { id: 'tron_oracle_neck',     name: 'Prayer Beads',          slot: 'NECK', sprite: 'gear/neck/oracle.png',       color: '#7d7bff', rarity: 'UNCOMMON', stats: { '+HEAL': 0.12, '+HP': 8 },              classRestriction: 'ORACLE',    setId: 'tron_set' },

  // ---- RING ----
  { id: 'tron_juggernaut_ring', name: 'Iron Signet',           slot: 'RING', sprite: 'gear/ring/juggernaut.png',   color: '#dc2626', rarity: 'UNCOMMON', stats: { '+DEF': 4 } },
  { id: 'tron_berserker_ring',  name: 'Hammered Iron Band',    slot: 'RING', sprite: 'gear/ring/berserker.png',    color: '#f55cc4', rarity: 'UNCOMMON', stats: { '+CRIT': 0.04 } },
  { id: 'tron_phantom_ring',    name: 'Silver Band',           slot: 'RING', sprite: 'gear/ring/phantom.png',      color: '#9bff5c', rarity: 'UNCOMMON', stats: { '+EVA': 0.05 } },
  { id: 'tron_tracer_ring',     name: 'Bronze Band',           slot: 'RING', sprite: 'gear/ring/tracer.png',       color: '#ff8c00', rarity: 'UNCOMMON', stats: { '+BURST': 0.05 } },
  { id: 'tron_scout_ring',      name: 'Carved Wood Ring',      slot: 'RING', sprite: 'gear/ring/scout.png',        color: '#ffc34d', rarity: 'UNCOMMON', stats: { '+DISC': 0.05 } },
  { id: 'tron_oracle_ring',     name: 'Quartz Ring',           slot: 'RING', sprite: 'gear/ring/oracle.png',       color: '#7d7bff', rarity: 'UNCOMMON', stats: { '+HEAL': 0.05 } },

  // ---- MAIN HAND (weapons) — the iconic per-class weapon ----
  { id: 'tron_juggernaut_weapon', name: 'War Hammer',          slot: 'MAIN', sprite: 'gear/weapons/juggernaut.png', color: '#dc2626', rarity: 'UNCOMMON', stats: { '+DMG': 18, '+CRIT': 0.05 },              classRestriction: 'JUGGERNAUT', setId: 'tron_set' },
  { id: 'tron_berserker_weapon',  name: 'Battle Axe',          slot: 'MAIN', sprite: 'gear/weapons/berserker.png',  color: '#f55cc4', rarity: 'UNCOMMON', stats: { '+DMG': 15, '+CRIT': 0.08 },              classRestriction: 'BERSERKER', setId: 'tron_set' },
  { id: 'tron_phantom_weapon',    name: 'Twin Daggers',        slot: 'MAIN', sprite: 'gear/weapons/phantom.png',    color: '#9bff5c', rarity: 'UNCOMMON', stats: { '+DMG': 12, '+EVA': 0.10, '+CRIT': 0.08 },  classRestriction: 'PHANTOM',   setId: 'tron_set' },
  { id: 'tron_tracer_weapon',     name: 'Short Sword',         slot: 'MAIN', sprite: 'gear/weapons/tracer.png',     color: '#ff8c00', rarity: 'UNCOMMON', stats: { '+DMG': 14, '+BURST': 0.12 },             classRestriction: 'TRACER',    setId: 'tron_set' },
  { id: 'tron_scout_weapon',      name: 'Recurve Bow',         slot: 'MAIN', sprite: 'gear/weapons/scout.png',      color: '#ffc34d', rarity: 'UNCOMMON', stats: { '+DMG': 13, '+CRIT': 0.10 },              classRestriction: 'SCOUT',     setId: 'tron_set' },
  { id: 'tron_oracle_weapon',     name: 'Glowing Orb',         slot: 'MAIN', sprite: 'items/tron_oracle_weapon.png', color: '#7d7bff', rarity: 'UNCOMMON', stats: { '+HEAL': 0.15, '+DMG': 8 },                classRestriction: 'ORACLE',    setId: 'tron_set' },

  // ============================================================
  // LEGACY ITEMS — kept around because users may own them from
  // earlier drops. Each gets its own unique sprite. The set_id
  // values (iron_pact) group the original tiered body sets for
  // a future set-bonus feature.
  // ============================================================

  // ---- BODY: plain shirts (per-class, common) ----
  { id: 'shirt_jugg_basic',      name: 'Iron Thread Vest',      slot: 'BODY', sprite: itemSprite('shirt_jugg_basic'),     color: '#dc2626', rarity: 'COMMON',    stats: { '+DMG': 5 },                              classRestriction: 'JUGGERNAUT' },
  { id: 'shirt_phantom_basic',   name: 'Mossy Wrap',            slot: 'BODY', sprite: itemSprite('shirt_phantom_basic'),  color: '#56e88e', rarity: 'COMMON',    stats: { '+EVA': 0.05 },                           classRestriction: 'PHANTOM' },
  { id: 'shirt_scout_basic',     name: 'Trail-Worn Tunic',      slot: 'BODY', sprite: itemSprite('shirt_scout_basic'),    color: '#daa520', rarity: 'COMMON',    stats: { '+DISC': 0.05 },                          classRestriction: 'SCOUT' },
  { id: 'shirt_berserker_basic', name: 'Rage-Bound Tunic',      slot: 'BODY', sprite: itemSprite('shirt_berserker_basic'),color: '#f55cc4', rarity: 'COMMON',    stats: { '+CRIT': 0.05 },                          classRestriction: 'BERSERKER' },
  { id: 'shirt_tracer_basic',    name: 'Lightstep Wrap',        slot: 'BODY', sprite: itemSprite('shirt_tracer_basic'),   color: '#ff8c00', rarity: 'COMMON',    stats: { '+BURST': 0.05 },                         classRestriction: 'TRACER' },
  { id: 'shirt_oracle_basic',    name: 'Stillness Robes',       slot: 'BODY', sprite: itemSprite('shirt_oracle_basic'),   color: '#8b9eff', rarity: 'COMMON',    stats: { '+HEAL': 0.05 },                          classRestriction: 'ORACLE' },
  { id: 'shirt_starter_universal', name: 'Plain Cotton',         slot: 'BODY', sprite: itemSprite('shirt_starter_universal'), color: '#14d6e8', rarity: 'COMMON', stats: { '+HP': 10 } },

  // ---- BODY: tiered armor (warrior bronze→steel, rogue shadow→whisper, healer linen→silk) ----
  { id: 'armor_warrior_1', name: 'Bronze Cuirass',           slot: 'BODY', sprite: itemSprite('armor_warrior_1'),       color: '#dc2626', rarity: 'UNCOMMON',  stats: { '+DMG': 8, '+DEF': 5 },                    classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'armor_warrior_2', name: 'Iron Cuirass',             slot: 'BODY', sprite: itemSprite('armor_warrior_2'),       color: '#dc2626', rarity: 'RARE',      stats: { '+DMG': 18, '+DEF': 12, '+HP': 30 },       classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'armor_warrior_3', name: 'Steel Cuirass',            slot: 'BODY', sprite: itemSprite('armor_warrior_3'),       color: '#dc2626', rarity: 'EPIC',      stats: { '+DMG': 35, '+DEF': 25, '+HP': 60, '+CRIT': 0.05 }, classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'armor_rogue_1',   name: 'Shadowed Leathers',         slot: 'BODY', sprite: itemSprite('armor_rogue_1'),         color: '#56e88e', rarity: 'UNCOMMON',  stats: { '+EVA': 0.10, '+CRIT': 0.05 },              classRestriction: 'PHANTOM' },
  { id: 'armor_rogue_2',   name: 'Whispering Leathers',       slot: 'BODY', sprite: itemSprite('armor_rogue_2'),         color: '#56e88e', rarity: 'RARE',      stats: { '+EVA': 0.18, '+CRIT': 0.10, '+DMG': 8 },   classRestriction: 'PHANTOM' },
  { id: 'armor_healer_1',  name: 'Linen Wraps',              slot: 'BODY', sprite: itemSprite('armor_healer_1'),        color: '#8b9eff', rarity: 'UNCOMMON',  stats: { '+HEAL': 0.10, '+HP': 20 },                classRestriction: 'ORACLE' },
  { id: 'armor_healer_2',  name: 'Silk Wraps',               slot: 'BODY', sprite: itemSprite('armor_healer_2'),        color: '#8b9eff', rarity: 'RARE',      stats: { '+HEAL': 0.18, '+HP': 40, '+DEF': 10 },    classRestriction: 'ORACLE' },

  // ---- HEAD ----
  { id: 'head_basic_hood',  name: "Traveler's Hood",         slot: 'HEAD', sprite: itemSprite('head_basic_hood'),       color: '#a8a8b8', rarity: 'COMMON',    stats: { '+DEF': 3 } },
  { id: 'head_warrior_1',   name: 'Bronze Helm',              slot: 'HEAD', sprite: itemSprite('head_warrior_1'),        color: '#dc2626', rarity: 'UNCOMMON',  stats: { '+DEF': 8, '+HP': 15 },                    classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'head_warrior_3',   name: 'Steel Helm',               slot: 'HEAD', sprite: itemSprite('head_warrior_3'),        color: '#dc2626', rarity: 'EPIC',      stats: { '+DEF': 25, '+HP': 50, '+DMG': 15 },       classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'head_rogue_1',    name: 'Shadow Hood',              slot: 'HEAD', sprite: itemSprite('head_rogue_1'),         color: '#56e88e', rarity: 'UNCOMMON',  stats: { '+EVA': 0.08, '+CRIT': 0.05 },              classRestriction: 'PHANTOM' },
  { id: 'head_rogue_3',    name: 'Whisper Cowl',             slot: 'HEAD', sprite: itemSprite('head_rogue_3'),         color: '#56e88e', rarity: 'EPIC',      stats: { '+EVA': 0.20, '+CRIT': 0.12, '+DMG': 10 },  classRestriction: 'PHANTOM' },
  { id: 'head_healer_1',   name: 'Cloth Band',               slot: 'HEAD', sprite: itemSprite('head_healer_1'),        color: '#8b9eff', rarity: 'UNCOMMON',  stats: { '+HEAL': 0.10, '+HP': 20 },                classRestriction: 'ORACLE' },
  { id: 'head_healer_3',   name: 'Mind Circlet',             slot: 'HEAD', sprite: itemSprite('head_healer_3'),        color: '#8b9eff', rarity: 'EPIC',      stats: { '+HEAL': 0.22, '+HP': 60, '+DEF': 18 },     classRestriction: 'ORACLE' },

  // ---- MAIN: weapons ----
  { id: 'weapon_warrior_1',    name: 'Iron Shortsword',        slot: 'MAIN', sprite: itemSprite('weapon_warrior_1'),     color: '#dc2626', rarity: 'COMMON',    stats: { '+DMG': 8 },                                 classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'weapon_warrior_2',    name: 'Steel Longsword',        slot: 'MAIN', sprite: itemSprite('weapon_warrior_2'),     color: '#dc2626', rarity: 'UNCOMMON',  stats: { '+DMG': 18, '+CRIT': 0.05 },                 classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'weapon_warrior_4',    name: 'Meteoric Greatsword',    slot: 'MAIN', sprite: itemSprite('weapon_warrior_4'),     color: '#dc2626', rarity: 'EPIC',      stats: { '+DMG': 50, '+CRIT': 0.15, '+HP': 40 },      classRestriction: 'JUGGERNAUT' },
  { id: 'weapon_rogue_0',      name: 'Twin Daggers',           slot: 'MAIN', sprite: itemSprite('weapon_rogue_0'),       color: '#56e88e', rarity: 'COMMON',    stats: { '+DMG': 6, '+EVA': 0.05 },                   classRestriction: 'PHANTOM' },
  { id: 'weapon_rogue_2',      name: 'Shadow Fangs',           slot: 'MAIN', sprite: itemSprite('weapon_rogue_2'),       color: '#56e88e', rarity: 'UNCOMMON',  stats: { '+DMG': 14, '+CRIT': 0.10, '+EVA': 0.10 },   classRestriction: 'PHANTOM' },
  { id: 'weapon_healer_1',     name: 'Walking Cane',           slot: 'MAIN', sprite: itemSprite('weapon_healer_1'),      color: '#8b9eff', rarity: 'COMMON',    stats: { '+HEAL': 0.05, '+DEF': 3 },                 classRestriction: 'ORACLE' },
  { id: 'weapon_healer_3',     name: 'Sagewood Staff',         slot: 'MAIN', sprite: itemSprite('weapon_healer_3'),      color: '#8b9eff', rarity: 'EPIC',      stats: { '+HEAL': 0.20, '+HP': 80, '+DMG': 10 },     classRestriction: 'ORACLE' },
  { id: 'weapon_burst_dagger', name: 'Lightning Stiletto',     slot: 'MAIN', sprite: itemSprite('weapon_burst_dagger'),  color: '#ff8c00', rarity: 'UNCOMMON',  stats: { '+BURST': 0.15, '+DMG': 12 },                classRestriction: 'TRACER' },
  { id: 'weapon_burst_axe',    name: 'Stormhatch',             slot: 'MAIN', sprite: itemSprite('weapon_burst_axe'),     color: '#ff8c00', rarity: 'RARE',      stats: { '+BURST': 0.20, '+DMG': 25, '+CRIT': 0.10 }, classRestriction: 'TRACER' },

  // ---- OFF: shields ----
  { id: 'shield_warrior_1', name: 'Wooden Round Shield',      slot: 'OFF', sprite: itemSprite('shield_warrior_1'),     color: '#dc2626', rarity: 'COMMON',    stats: { '+DEF': 5, '+HP': 10 },                    classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'shield_warrior_3', name: 'Steel Bulwark',            slot: 'OFF', sprite: itemSprite('shield_warrior_3'),     color: '#dc2626', rarity: 'RARE',      stats: { '+DEF': 18, '+HP': 35, '+DMG': 8 },       classRestriction: 'JUGGERNAUT', setId: 'iron_pact' },
  { id: 'shield_rogue_1',   name: 'Buckler of Whispers',      slot: 'OFF', sprite: itemSprite('shield_rogue_1'),       color: '#56e88e', rarity: 'UNCOMMON',  stats: { '+EVA': 0.10, '+DEF': 5 },                 classRestriction: 'PHANTOM' },
  { id: 'shield_healer_1',  name: 'Tome of Rest',             slot: 'OFF', sprite: itemSprite('shield_healer_1'),      color: '#8b9eff', rarity: 'COMMON',    stats: { '+HEAL': 0.08, '+HP': 15 },                classRestriction: 'ORACLE' },
  { id: 'shield_healer_3',  name: 'Codex of Mending',         slot: 'OFF', sprite: itemSprite('shield_healer_3'),      color: '#8b9eff', rarity: 'EPIC',      stats: { '+HEAL': 0.20, '+HP': 50, '+DEF': 15 },    classRestriction: 'ORACLE' },

  // ---- NECK ----
  { id: 'neck_bloodstone', name: 'Bloodstone Pendant',        slot: 'NECK', sprite: itemSprite('neck_bloodstone'),      color: '#dc2626', rarity: 'UNCOMMON',  stats: { '+DMG': 12, '+CRIT': 0.05 } },
  { id: 'neck_amber',      name: 'Amber Focus',               slot: 'NECK', sprite: itemSprite('neck_amber'),           color: '#daa520', rarity: 'UNCOMMON',  stats: { '+HEAL': 0.10, '+DISC': 0.10 } },
  { id: 'neck_legendary_compass', name: 'Compass of the Pathfinders', slot: 'NECK', sprite: itemSprite('neck_legendary_compass'), color: '#daa520', rarity: 'LEGENDARY', stats: { '+DISC': 0.30, '+XP': 0.10, '+GOLD': 0.05 }, classRestriction: 'SCOUT' },

  // ---- RING (universal — no classRestriction) ----
  { id: 'ring_iron_band',    name: 'Iron Band',                slot: 'RING', sprite: itemSprite('ring_iron_band'),       color: '#a8a8b8', rarity: 'COMMON',    stats: { '+DEF': 3 } },
  { id: 'ring_lucky',        name: 'Lucky Coin',               slot: 'RING', sprite: itemSprite('ring_lucky'),           color: '#ffc34d', rarity: 'UNCOMMON',  stats: { '+GOLD': 0.10, '+DISC': 0.05 } },
  { id: 'ring_focus',        name: 'Ring of Focus',            slot: 'RING', sprite: itemSprite('ring_focus'),           color: '#8b9eff', rarity: 'UNCOMMON',  stats: { '+XP': 0.05, '+HEAL': 0.05 } },
  { id: 'ring_mythic_blood', name: 'Band of the Berserker',    slot: 'RING', sprite: itemSprite('ring_mythic_blood'),    color: '#dc2626', rarity: 'MYTHIC',    stats: { '+DMG': 100, '+CRIT': 0.30, '+HP': 100, '+BURST': 0.30, '+DEF': 50 } },

  // ---- HANDS (universal) ----
  { id: 'hands_gauntlets_iron', name: 'Iron Gauntlets',        slot: 'HANDS', sprite: itemSprite('hands_gauntlets_iron'), color: '#a8a8b8', rarity: 'COMMON',    stats: { '+DMG': 5, '+DEF': 3 } },
  { id: 'hands_rogue_wraps',    name: 'Silent Wraps',         slot: 'HANDS', sprite: itemSprite('hands_rogue_wraps'),    color: '#56e88e', rarity: 'UNCOMMON',  stats: { '+CRIT': 0.08, '+EVA': 0.05 } },

  // ---- FEET (universal) ----
  { id: 'feet_traveler_boots', name: "Traveler's Boots",       slot: 'FEET', sprite: itemSprite('feet_traveler_boots'),  color: '#a8a8b8', rarity: 'COMMON',    stats: { '+HP': 15, '+DISC': 0.05 } },
  { id: 'feet_swift_boots',    name: 'Swift Boots',            slot: 'FEET', sprite: itemSprite('feet_swift_boots'),     color: '#56e88e', rarity: 'UNCOMMON',  stats: { '+EVA': 0.08, '+BURST': 0.05 } },
];

export async function seedItems() {
  for (const item of ITEMS) {
    await prisma.itemDef.upsert({
      where: { id: item.id },
      create: {
        id: item.id,
        name: item.name,
        description: item.description ?? null,
        slot: item.slot,
        sprite: item.sprite,
        color: item.color,
        rarity: item.rarity,
        stats: item.stats as any,
        classRestriction: item.classRestriction ?? null,
        setId: item.setId ?? null,
      },
      update: {
        name: item.name,
        description: item.description ?? null,
        slot: item.slot,
        sprite: item.sprite,
        color: item.color,
        rarity: item.rarity,
        stats: item.stats as any,
        classRestriction: item.classRestriction ?? null,
        setId: item.setId ?? null,
      },
    });
  }
  console.log(`[seed] upserted ${ITEMS.length} ItemDef rows`);
}

if (process.argv[1]?.endsWith('seedItems.ts') || process.argv[1]?.endsWith('seedItems.js')) {
  seedItems()
    .then(() => prisma.$disconnect())
    .catch((e) => {
      console.error(e);
      prisma.$disconnect();
      process.exit(1);
    });
}
