-- Rename ShieldTier enum value BREECHED -> BREACHED.
--
-- Split across two migrations because Postgres refuses to use a
-- newly-added enum value within the same transaction that added it
-- (error 55P04: "unsafe use of new value"). So this file only
-- does the ADD VALUE. The companion migration
-- "20260627000000_breached_data_migration" runs after this and
-- performs the UPDATE on a separate transaction.
--
-- Old BREECHED label stays in the enum (Debian Postgres 17.10 build
-- has DROP VALUE disabled). The Prisma client only knows the 4
-- current values, so the legacy value is unreferenced. New DBs on
-- a future reset get a clean enum.
ALTER TYPE "ShieldTier" ADD VALUE IF NOT EXISTS 'BREACHED';
