import { Decoder, Stream } from '@garmin/fitsdk';
import fs from 'fs';
const path = process.argv[2];
const buf = fs.readFileSync(path);
const stream = Stream.fromBuffer(buf);
const decoder = new Decoder(stream);
const { messages, errors } = decoder.read();
console.log('errors:', errors);
console.log('sessionMesg:', JSON.stringify(messages.sessionMesgs?.[0], null, 2));
console.log('recordMesgs count:', messages.recordMesgs?.length);
console.log('sample record[0]:', JSON.stringify(messages.recordMesgs?.[0]));
const mid = Math.floor((messages.recordMesgs?.length||1)/2);
console.log('sample record[mid]:', JSON.stringify(messages.recordMesgs?.[mid]));
